export const CONFIG = {
  EVENT: {
    name: '章魚燒大胃王挑戰賽',
    visualTitle: 'TAKOYAKI BATTLE 極限章魚燒王',
    subtitle: '滾燙章魚燒 等你來挑戰',
    date: '2026-07-19',
    dateDisplay: '2026年7月19日（週日）',
    venue: '愛廣場｜台中一中街商圈',
    registerStart: '2026-06-22',
    registerEnd: '2026-07-10',
    fee: 600,
    totalSlots: 30,
    organizer: '明仁二代目',
  },
  SOCIAL: {
    instagram: 'https://www.instagram.com/takoyaki.tw/',
    facebook: '',
    lineOA: import.meta.env.VITE_LINE_OA_URL || '',
  },
  WEBHOOK: {
    register: import.meta.env.VITE_REGISTER_WEBHOOK_URL || '',
    vote: import.meta.env.VITE_VOTE_WEBHOOK_URL || '',
    voteResults: import.meta.env.VITE_VOTE_RESULTS_WEBHOOK_URL || '',
  },
  LIFF: {
    id: import.meta.env.VITE_LIFF_ID || '',
  },
  STAGES: [
    {
      id: 1,
      code: 'STAGE 01',
      name: '極速章魚燒',
      desc: '最快吃完12顆，前18名晉級',
      duration: '約20分鐘',
      players: '30人 → 前18人晉級',
      rules: '每位參賽者面前放置12顆章魚燒（原味），裁判喊開始同時計時，吃完後舉手，裁判驗盤（盤面清空才算數），依完成時間排序最快完成的前18人晉級。',
      image: '/assets/stages/stage-01-speed.png',
      difficulty: 1,
      obstacles: [] as { name: string; effect: string }[],
    },
    {
      id: 2,
      code: 'STAGE 02',
      name: '極樂章魚燒',
      desc: '趣味障礙卡登場，完成3盒者晉級',
      duration: '約20分鐘',
      players: '18人，完成3盒（36顆）晉級',
      rules: '18人同場開吃，章魚燒每12顆為一單位持續補盤，時間內吃完3盒者晉級，全程禁止補充飲品，趣味障礙卡隨機登場。',
      image: '/assets/stages/stage-02-chaos.png',
      difficulty: 3,
      obstacles: [
        { name: '是芥末日卡', effect: '章魚燒擠芥末' },
        { name: '好氣好氣卡', effect: '需喝漂浮可樂' },
        { name: 'ㄋㄟㄋㄟ補給卡', effect: '奶茶補給（例外飲品）' },
        { name: '冰火九重卡', effect: '冰火章魚燒（冷熱交替）' },
        { name: '超級進化卡', effect: '超級綜合章魚燒（所有口味疊加）' },
      ],
    },
    {
      id: 3,
      code: 'STAGE 03',
      name: '極限章魚燒',
      desc: '無限補盤，吃最多者奪冠',
      duration: '約15分鐘',
      players: '晉級者全員，前3名獲獎',
      rules: '所有晉級者同場開吃，章魚燒持續補盤不中斷，時間到以裁判驗盤顆數為準，吃最多的前3名獲獎，同顆數者以最後一顆完成時間較早者優先。',
      image: '/assets/stages/stage-03-limit.png',
      difficulty: 5,
    },
  ],
  PRIZES: [
    { rank: 1, label: 'CHAMPION', title: '極限章魚燒王', amount: 20000 },
    { rank: 2, label: '2ND PLACE', title: '亞軍', amount: 5000 },
    { rank: 3, label: '3RD PLACE', title: '季軍', amount: 3000 },
  ],
  PROCESS: [
    { step: '01', title: '線上填表', desc: '填寫報名表單，提交基本資料' },
    { step: '02', title: '主辦審核', desc: '主辦方確認報名資格後通知' },
    { step: '03', title: '繳費 NT$600', desc: '完成繳費取得報名資格' },
    { step: '04', title: '收取參賽物資', desc: 'T-shirt + 毛巾 + 頭巾三件組' },
    { step: '05', title: '現場簽到', desc: '比賽當天完成簽到及規則認同' },
  ],
  MERCH: [
    { name: '賽事限定T-shirt', image: '/assets/merchandise/merch-tshirt.jpg', included: true },
    { name: '決戰擦汗毛巾', image: '/assets/merchandise/merch-towel.jpg', included: true },
    { name: '烈火鬥志頭巾', image: '/assets/merchandise/merch-headband.jpg', included: true },
    { name: '雙面意志扇', image: '/assets/merchandise/merch-fan.jpg', included: true },
    { name: '章魚燒兌換券', image: '/assets/merchandise/merch-voucher.jpg', included: true },
  ],
}
